kind: pipeline
name: default
steps:

  - name: test
    image: node:alpine
    pull: true
    commands:
      - yarn install
      - yarn build
      - yarn test

  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
    when:
      status: success
      event: tag

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
